Update Action

diff --git a/.github/actions/release-setup/action.yaml b/.github/actions/release-setup/action.yaml
--- a/.github/actions/release-setup/action.yaml
+++ b/.github/actions/release-setup/action.yaml
@@ -31,8 +31,19 @@ runs:
   - name: Install Crossplane CLI
     shell: bash
     run: |
-      set -x
-      curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh" | sh
+      install-script="$(curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh")"
+      ending_time=$(($(date +%s) + 60))
+      until command -v crossplane >/dev/null 2>&1; do
+          if [ $(date +%s) -gt $ending_time ]; then
+              echo "Timeout while installing Crossplane CLI"
+              exit 1
+          fi
+          sleep 5
+          echo "Crossplane CLI not found, installing..."
+          if ! echo "$install-script" | sh; then
+              echo "Failed to install Crossplane CLI, retrying..."
+          fi
+      done
       sudo mv crossplane /usr/local/bin/
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v6
