rename files

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -1,280 +1,63 @@
-name: Create Release PR
-run-name: Create Release PR for ${{ inputs.version }}
+name: Create Release
+run-name: "Create Release from #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"
 
 on:
-  workflow_dispatch:
-    inputs:
-      version:
-        description: "Version number (e.g. v1.2.3)"
-        required: true
-        type: string
-      branch-to-release:
-        description: "Branch to release (default: main)"
-        required: false
-        type: string
-        default: "main"
-
-env:
-  ECR_REGISTRY_ADDRESS: "public.ecr.aws/w5n9a2g2"
-  VERSION_NR: ${{ inputs.version }}
+  pull_request:
+    types: [closed]
+    branches:
+      - main*
 
 jobs:
-  create-branch:
-    name: Create Branch for Release
+  create-release:
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      packages: write
+    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
     steps:
-      - name: Check Version Number Format
-        env:
-          SEMVER_EXP: 'v[0-9]\.[0-9]\.[0-9](-[-.A-z0-9]+)?'
+      - name: Parse PR Body
+        id: parse-pr-body
         run: |
-          if ! echo "$VERSION_NR" | grep -E "^$SEMVER_EXP"'$' -q; then
-              echo "illegal version number $VERSION_NR.\n\n" \
-                  "Please use a version number that matches this regular" \
-                  "expression: $SEMVER_EXP"
-              exit 1
+          VERSION_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -E '^\[version-number: [^]]+\]::$' | sed 's/\[version-number: //;s/\]:://')
+          if [[ -z "$VERSION_NUMBER" ]]; then
+            echo "Error: Version number not found in PR body."
+            exit 1
           fi
-      - name: Checkout klutchio
-        uses: actions/checkout@v6
+          RUN_ID=$(echo "${{ github.event.pull_request.body }}" | grep -E '^\[run-id: [^]]+\]::$' | sed 's/\[run-id: //;s/\]:://')
+          if [[ -z "$RUN_ID" ]]; then
+            echo "Error: RunID not found in PR body."
+            exit 1
+          fi
+          (
+            echo "version-number=$VERSION_NUMBER"
+            echo "run-id=$RUN_ID"
+          ) >> $GITHUB_OUTPUT
+
+      - name: Download all binaries
+        uses: actions/download-artifact@v4
         with:
-          ref: ${{ inputs.branch-to-release }}
-          fetch-depth: 0
-      - name: Create release branch
-        run: |
-          git checkout -b "releases/${{ inputs.version }}"
-          git push -u origin "releases/${{ inputs.version }}"
-  create-konnector-images:
-    name: Build and Push Konnector Images
-    needs: create-branch
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      packages: write
-    steps:
-      - name: Checkout klutchio
-        uses: actions/checkout@v6
+          pattern: klutch-bind-*
+          merge-multiple: true
+          path: binaries/
+          run-id: ${{ steps.parse-pr-body.outputs.run-id }}
+          github-token: ${{ github.token }}
+      - name: Create GitHub Release
+        uses: softprops/action-gh-release@v2
         with:
-          ref: releases/${{ inputs.version }}
-          fetch-depth: 0
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v6
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-      - name: Setup Go
-        uses: actions/setup-go@v6
-        with:
-          go-version-file: bind/go.mod
-          cache-dependency-path: "**/go.sum"
-      - name: Install ko
-        uses: ko-build/setup-ko@v0.9
-        env:
-          KO_DOCKER_REPO: "public.ecr.aws/w5n9a2g2"
-      - name: Cache ko build
-        uses: actions/cache@v5
-        with:
-          path: /tmp/ko
-          key: ko-build-${{ hashFiles('**/go.sum', '**/*.go') }}
-          restore-keys: ko-build-
-        env:
-          KOCACHE: /tmp/ko
-      - name: Build and push images
-        env:
-          KOCACHE: /tmp/ko
-        working-directory: bind
-        run: |
-          $GITHUB_WORKSPACE/.github/bin/build_with_ko.sh "./cmd/konnector" \
-              "${ECR_REGISTRY_ADDRESS}/klutch/konnector" \
-              "${VERSION_NR}"
-  create-example-backend-images:
-    name: Build and Push Example Backend Images
-    needs: create-branch
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      packages: write
-    steps:
-      - name: Checkout klutchio
-        uses: actions/checkout@v6
-        with:
-          ref: releases/${{ inputs.version }}
-          fetch-depth: 0
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v6
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-      - name: Setup Go
-        uses: actions/setup-go@v6
-        with:
-          go-version-file: bind/go.mod
-          cache-dependency-path: "**/go.sum"
-      - name: Install ko
-        uses: ko-build/setup-ko@v0.9
-        env:
-          KO_DOCKER_REPO: "public.ecr.aws/w5n9a2g2"
-      - name: Cache ko build
-        uses: actions/cache@v5
-        with:
-          path: /tmp/ko
-          key: ko-build-${{ hashFiles('**/go.sum', '**/*.go') }}
-          restore-keys: ko-build-
-        env:
-          KOCACHE: /tmp/ko
-      - name: Build and push images
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-          KOCACHE: /tmp/ko
-        working-directory: bind
-        run: |
-          $GITHUB_WORKSPACE/.github/bin/build_with_ko.sh "./cmd/example-backend" \
-          "${ECR_REGISTRY_ADDRESS}/klutch/example-backend" \
-          "${VERSION_NR}"
-  create-provider-anynines-controller-images:
-    name: Build and Push Provider anynines Controller Images
-    needs: create-branch
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      packages: write
-    steps:
-      - name: Checkout klutchio
-        uses: actions/checkout@v6
-        with:
-          ref: releases/${{ inputs.version }}
-          fetch-depth: 0
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v6
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-      - name: Setup Go
-        uses: actions/setup-go@v6
-        with:
-          go-version-file: bind/go.mod
-          cache-dependency-path: "**/go.sum"
-      - name: Build and push images
-        working-directory: provider-anynines
-        env:
-          BUILDX_NO_DEFAULT_ATTESTATIONS: "1"
-        run: |
-          $GITHUB_WORKSPACE/.github/bin/provider_anynines_make.sh "buildx.all" \
-              "${ECR_REGISTRY_ADDRESS}" \
-              "${VERSION_NR}"
-  create-provider-anynines-image:
-    name: Build and Push Crossplane Config Images
-    needs: create-branch
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      packages: write
-    steps:
-      - name: Checkout klutchio
-        uses: actions/checkout@v6
-        with:
-          ref: releases/${{ inputs.version }}
-          fetch-depth: 0
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v6
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-      - name: Install Crossplane CLI
-        uses: crossplane-contrib/setup-crossplane-action@main
-        with:
-          version: v1.20.9
-      - name: Build and Push Provider anynines Config Image
-        working-directory: provider-anynines
-        run: |
-          $GITHUB_WORKSPACE/.github/bin/provider_anynines_make.sh "provider-build-push" \
-              "${ECR_REGISTRY_ADDRESS}" \
-              "${VERSION_NR}"
-      - name: Build and Push Dataservices Config Image
-        working-directory: crossplane-api
-        run: |
-          $GITHUB_WORKSPACE/.github/bin/provider_anynines_make.sh "dataservices-config-push" \
-              "${ECR_REGISTRY_ADDRESS}" \
-              "${VERSION_NR}"
-  create-klutch-bind-binaries:
-    name: Build and Push Klutch-Bind Binaries
-    needs: create-branch
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        goos: ["linux", "darwin", "windows"]
-        goarch: ["amd64", "arm64", "386"]
-        exclude:
-          - goos: darwin
-            goarch: "386"
-    permissions:
-      contents: write
-      packages: write
-    steps:
-      - name: Checkout klutchio
-        uses: actions/checkout@v6
-        with:
-          ref: releases/${{ inputs.version }}
-          fetch-depth: 0
-      - name: Setup Go
-        uses: actions/setup-go@v6
-        with:
-          go-version-file: bind/go.mod
-          cache-dependency-path: "**/go.sum"
-      - name: Build klutch-bind binary
-        env:
-          GOOS: ${{ matrix.goos }}
-          GOARCH: ${{ matrix.goarch }}
-        working-directory: bind
-        run: |
-          $GITHUB_WORKSPACE/.github/bin/go_build_klutch-bind_helper_binary.sh "${GOOS}" "${GOARCH}"
-      - name: Upload klutch-bind binary
-        uses: actions/upload-artifact@v7
-        with:
-          name: klutch-bind-${{ matrix.goos }}-${{ matrix.goarch }}
-          path: ./klutch-bind-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
-  update-version-refs:
-    name: Update Manifests
-    needs:
-    - create-konnector-images
-    - create-example-backend-images
-    - create-provider-anynines-controller-images
-    - create-provider-anynines-image
-    - create-klutch-bind-binaries
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      packages: write
-      pull-requests: write
-    steps:
-      - name: Checkout klutchio
-        uses: actions/checkout@v6
-        with:
-          ref: releases/${{ inputs.version }}
-          fetch-depth: 0
-      - name: Install yq
-        uses: mikefarah/yq@v4.9.8
-      - name: Update manifests with new image tags
-        run: |
-          $GITHUB_WORKSPACE/.github/bin/update_version_refs_in_manifests.sh "${VERSION_NR}" \
-              "${ECR_REGISTRY_ADDRESS}"
-      - name: Update ChangeLog
-        run: |
-          $GITHUB_WORKSPACE/.github/bin/update_changelog.sh "${VERSION_NR}"
-      - name: Commit and push changes
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add -A
-          git commit -m "${{ inputs.version }}" || echo "No changes to commit"
-          git push
-      - name: Open PR
+          target_commitish: ${{ github.event.pull_request.head.sha }}
+          tag_name: ${{ steps.parse-pr-body.outputs.version-number }}
+          name: ${{ steps.parse-pr-body.outputs.version-number }}
+          token: ${{ github.token }}
+          generate_release_notes: true
+          files: binaries/*
+      - name: Delete binary artifacts
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          $GITHUB_WORKSPACE/.github/bin/create_pr.sh "${{ inputs.version }}" "${{ inputs.branch-to-release }}" "${{ github.run_id }}"
+          ENDPOINT="$(printf '/repos/%s/actions/runs/%s/artifacts' \
+            "${{ github.repository }}" \
+            "${{ steps.parse-pr-body.outputs.run-id }}"
+          )"
+          ARTIFACTS=$(gh api -H "Accept: application/vnd.github+json" "$ENDPOINT" --jq '.artifacts[] | .id')
+          for artifact_id in $ARTIFACTS; do
+            echo "Deleting artifact with ID: $artifact_id"
+            gh api -X DELETE -H "Accept: application/vnd.github+json" \
+              "/repos/${{ github.repository }}/actions/artifacts/$artifact_id"
+          done
