Retrieve Artifacts accross runs

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -12,23 +12,37 @@ jobs:
     runs-on: ubuntu-latest
     if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
     steps:
-      - name: Strip 'releases/' prefix from source branch
-        id: branch_name
+      - name: Parse PR Body
+        id: parse-pr-body
         run: |
-          raw="${{ github.event.pull_request.head.ref }}"
-          echo "value=${raw#releases/}" >> "$GITHUB_OUTPUT"
+          VERSION_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -E '^< !-- version-number: [^ ]+ -->' | sed 's/< !-- version-number: //;s/ -->//')
+          if [[ -z "$VERSION_NUMBER" ]]; then
+            echo "Error: Version number not found in PR body."
+            exit 1
+          fi
+          RUN_ID=$(echo "${{ github.event.pull_request.body }}" | grep -E '^< !-- run-id: [^ ]+ -->' | sed 's/< !-- run-id: //;s/ -->//')
+          if [[ -z "$RUN_ID" ]]; then
+            echo "Error: RunID not found in PR body."
+            exit 1
+          fi
+          (
+            echo "version-number=$VERSION_NUMBER"
+            echo "run-id=$RUN_ID"
+          ) >> $GITHUB_OUTPUT
+
       - name: Download all binaries
         uses: actions/download-artifact@v4
         with:
           pattern: klutch-bind-*
           merge-multiple: true
           path: binaries/
+          run-id: ${{ steps.parse-pr-body.outputs.run-id }}
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v2
         with:
           target_commitish: ${{ github.event.pull_request.head.sha }}
-          tag_name: ${{ steps.branch_name.outputs.value }}
-          name: ${{ steps.branch_name.outputs.value }}
+          tag_name: ${{ steps.parse-pr-body.outputs.version-number }}
+          name: ${{ steps.parse-pr-body.outputs.version-number }}
           token: ${{ github.token }}
           generate_release_notes: true
           files: binaries/*
